/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import entidades.Registro;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import utilidades.TodoJson;

/**
 *
 * @author USUARIO
 */
public class ListadoRegistro extends javax.swing.JFrame {

    List<Registro> listaRegistros = new ArrayList<>();
    
    File archivo;

    public void setArchivo(File archivo) {
        this.archivo = archivo;
    }
    
    boolean comboActivo = false;
    
    Principal principal;

    public void setPrincipal(Principal principal) {
        this.principal = principal;
    }
    
    public ListadoRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new Diseño.Background();
        panelPrinc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new Diseño.Button();
        jLabel2 = new javax.swing.JLabel();
        labelNivel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelEmpleado = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelVehiculo = new javax.swing.JLabel();
        comboRegistro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        labelZona = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelHoraEntrada = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelFechaEntrada = new javax.swing.JLabel();
        labelFechaSalida = new javax.swing.JLabel();
        labelHoraSalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1.setBlur(panelPrinc);
        background1.setImage(new javax.swing.ImageIcon(getClass().getResource("/recursos/carroFondo8.jpg"))); // NOI18N

        panelPrinc.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado Registros");

        btnVolver.setText("Volver");
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID Registro:");

        labelNivel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelNivel.setForeground(new java.awt.Color(255, 255, 255));
        labelNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Zona:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hora Entrada:");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hora Salida:");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cliente");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Empleado");

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Vehículo");

        labelEmpleado.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        labelEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelCliente.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nombre:");

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Marca:");

        labelVehiculo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        labelVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        comboRegistro.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        comboRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRegistroActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nivel:");

        labelZona.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelZona.setForeground(new java.awt.Color(255, 255, 255));
        labelZona.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelZona.setText("adaw");

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Fecha Salida:");

        labelHoraEntrada.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelHoraEntrada.setForeground(new java.awt.Color(255, 255, 255));
        labelHoraEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Fecha Entrada:");

        labelFechaEntrada.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelFechaEntrada.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelFechaSalida.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelFechaSalida.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelHoraSalida.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelHoraSalida.setForeground(new java.awt.Color(255, 255, 255));
        labelHoraSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPrincLayout = new javax.swing.GroupLayout(panelPrinc);
        panelPrinc.setLayout(panelPrincLayout);
        panelPrincLayout.setHorizontalGroup(
            panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelPrincLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addComponent(comboRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelPrincLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addGap(5, 5, 5)
                .addComponent(labelNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelZona, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jLabel13)
                .addGap(12, 12, 12)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9))
                    .addComponent(labelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panelPrincLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)))
                .addGap(7, 7, 7)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addComponent(jLabel12)
                .addGap(12, 12, 12)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8))
                    .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panelPrincLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel15)
                .addGap(10, 10, 10)
                .addComponent(labelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(jLabel10))
            .addGroup(panelPrincLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(labelHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jLabel14)
                .addGap(15, 15, 15)
                .addComponent(labelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelPrincLayout.createSequentialGroup()
                .addGap(692, 692, 692)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPrincLayout.setVerticalGroup(
            panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labelZona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13))
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(labelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6))
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addComponent(labelFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(labelHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel12))
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addGap(16, 16, 16)
                        .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(labelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(labelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(labelHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background1.add(panelPrinc);
        panelPrinc.setBounds(30, 20, 810, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void comboRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRegistroActionPerformed
        if (!comboActivo) {
            return;
        }
        Registro registro = listaRegistros.get(comboRegistro.getSelectedIndex());
        labelNivel.setText(registro.getNivel());
        labelZona.setText(registro.getZona());
        labelFechaEntrada.setText(registro.getFechaIngreso());
        labelHoraEntrada.setText(registro.getHoraIngreso());
        labelCliente.setText(registro.getCliente().getNombresApellidos());
        labelEmpleado.setText(registro.getEmpleado().getNombresApellidos());
        labelVehiculo.setText(registro.getVehiculo().getMarcaModelo());
        if (registro.getFechaSalida().equals("null")) {
            labelFechaSalida.setText("Aún no a salido");
        }else{
            labelFechaSalida.setText(registro.getFechaSalida());
        }
        if (registro.getHoraSalida().equals("null")) {
            labelHoraSalida.setText("Aún no a salido");
        }else{
            labelHoraSalida.setText(registro.getHoraSalida());
        }
    }//GEN-LAST:event_comboRegistroActionPerformed

    public void rellenar(){
        comboActivo = false;
        listaRegistros = TodoJson.obtenerListaRegistros(archivo);
        comboRegistro.removeAllItems();
        if (!(listaRegistros.isEmpty())) {
            for(Registro registro : listaRegistros){
                comboRegistro.addItem(registro.getIdRegistro());
            }
            Registro registro = listaRegistros.get(0);
            labelNivel.setText(registro.getNivel());
            labelZona.setText(registro.getZona());
            labelFechaEntrada.setText(registro.getFechaIngreso());
            labelHoraEntrada.setText(registro.getHoraIngreso());
            labelCliente.setText(registro.getCliente().getNombresApellidos());
            labelEmpleado.setText(registro.getEmpleado().getNombresApellidos());
            labelVehiculo.setText(registro.getVehiculo().getMarcaModelo());
            if (registro.getFechaSalida().equals("null")) {
                labelFechaSalida.setText("Aún no a salido");
            }else{
                labelFechaSalida.setText(registro.getFechaSalida());
            }
            if (registro.getHoraSalida().equals("null")) {
                labelHoraSalida.setText("Aún no a salido");
            }else{
                labelHoraSalida.setText(registro.getHoraSalida());
            }
        }
        comboActivo = true;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Diseño.Background background1;
    private Diseño.Button btnVolver;
    private javax.swing.JComboBox<String> comboRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JLabel labelFechaEntrada;
    private javax.swing.JLabel labelFechaSalida;
    private javax.swing.JLabel labelHoraEntrada;
    private javax.swing.JLabel labelHoraSalida;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelVehiculo;
    private javax.swing.JLabel labelZona;
    private javax.swing.JPanel panelPrinc;
    // End of variables declaration//GEN-END:variables
}
