/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.io.File;
import javax.swing.JOptionPane;
import paneles.Registros;
import utilidades.TodoJson;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {

    File archivo;
    Entrada entrada = new Entrada();
    Salida salida = new Salida();
    public Principal() {
        initComponents();
        btnRegisCliente.setEnabled(false);
        btnRegisEmple.setEnabled(false);
        btnRegisVehiculo.setEnabled(false);
        btnRegisEntrada.setEnabled(false);
        btnRegisSalida.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new Diseño.Background();
        panelPrinc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new Diseño.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegisCliente = new Diseño.Button();
        btnRegisEmple = new Diseño.Button();
        btnRegisVehiculo = new Diseño.Button();
        btnRegisEntrada = new Diseño.Button();
        btnRegisSalida = new Diseño.Button();
        btnSelecArchivo = new Diseño.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1.setBlur(panelPrinc);
        background1.setImage(new javax.swing.ImageIcon(getClass().getResource("/recursos/carroFondo5.png"))); // NOI18N

        panelPrinc.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Estacionamiento");

        button1.setText("SALIR");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registrar Entidades");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registrar Entradas/Salidas");

        btnRegisCliente.setText("Registrar Cliente");
        btnRegisCliente.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnRegisCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisClienteActionPerformed(evt);
            }
        });

        btnRegisEmple.setText("Registrar Empleado");
        btnRegisEmple.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnRegisEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisEmpleActionPerformed(evt);
            }
        });

        btnRegisVehiculo.setText("Registrar vehículo");
        btnRegisVehiculo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnRegisVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisVehiculoActionPerformed(evt);
            }
        });

        btnRegisEntrada.setText("Registrar Entrada");
        btnRegisEntrada.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnRegisEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisEntradaActionPerformed(evt);
            }
        });

        btnRegisSalida.setText("Registrar Salida");
        btnRegisSalida.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnRegisSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisSalidaActionPerformed(evt);
            }
        });

        btnSelecArchivo.setText("Seleccionar Archivo");
        btnSelecArchivo.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btnSelecArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincLayout = new javax.swing.GroupLayout(panelPrinc);
        panelPrinc.setLayout(panelPrincLayout);
        panelPrincLayout.setHorizontalGroup(
            panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincLayout.createSequentialGroup()
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnRegisEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegisVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegisCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincLayout.createSequentialGroup()
                        .addComponent(btnSelecArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))))))
        );
        panelPrincLayout.setVerticalGroup(
            panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegisCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegisEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegisVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegisEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegisSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(153, 153, 153))
                    .addGroup(panelPrincLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        background1.add(panelPrinc);
        panelPrinc.setBounds(60, 30, 820, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_button1ActionPerformed

    private void btnRegisClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisClienteActionPerformed
        Registros registro = new Registros();
        registro.registroCliente(this);
        if (registro.getCliente()==null) {
            return;
        }
        TodoJson.agregarCliente(archivo, registro.getCliente());
        JOptionPane.showMessageDialog(this, "Se registró correctamente");
    }//GEN-LAST:event_btnRegisClienteActionPerformed

    private void btnRegisEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisEmpleActionPerformed
        Registros registro = new Registros();
        registro.registroEmpleado(this);
        if (registro.getEmpleado()==null) {
            return;
        }
        TodoJson.agregarEmpleado(archivo, registro.getEmpleado());
        JOptionPane.showMessageDialog(this, "Se registró correctamente");
    }//GEN-LAST:event_btnRegisEmpleActionPerformed

    private void btnRegisVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisVehiculoActionPerformed
        Registros registro = new Registros();
        registro.registroVehiculo(this);
        if (registro.getVehiculo()==null) {
            return;
        }
        TodoJson.agregarVehiculo(archivo, registro.getVehiculo());
        JOptionPane.showMessageDialog(this, "Se registró correctamente");
    }//GEN-LAST:event_btnRegisVehiculoActionPerformed

    private void btnRegisEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisEntradaActionPerformed
        entrada.setPrincipal(this);
        entrada.setLocationRelativeTo(this);
        entrada.setArchivo(archivo);
        entrada.rellenar();
        entrada.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegisEntradaActionPerformed

    private void btnSelecArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecArchivoActionPerformed
        archivo = TodoJson.selecArchivo();
        if (!(archivo == null)) {
            JOptionPane.showMessageDialog(this, "Archivo cargado correctamente");
            btnRegisCliente.setEnabled(true);
            btnRegisEmple.setEnabled(true);
            btnRegisVehiculo.setEnabled(true);
            btnRegisEntrada.setEnabled(true);
            btnRegisSalida.setEnabled(true);
        }
    }//GEN-LAST:event_btnSelecArchivoActionPerformed

    private void btnRegisSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisSalidaActionPerformed
        salida.setPrincipal(this);
        salida.setLocationRelativeTo(this);
        salida.setArchivo(archivo);
        salida.rellenar();
        salida.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegisSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Diseño.Background background1;
    private Diseño.Button btnRegisCliente;
    private Diseño.Button btnRegisEmple;
    private Diseño.Button btnRegisEntrada;
    private Diseño.Button btnRegisSalida;
    private Diseño.Button btnRegisVehiculo;
    private Diseño.Button btnSelecArchivo;
    private Diseño.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelPrinc;
    // End of variables declaration//GEN-END:variables
}
