/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import entidades.Registro;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import utilidades.TodoJson;

/**
 *
 * @author USUARIO
 */
public class Salida extends javax.swing.JFrame {

    List<Registro> listaRegistros = new ArrayList<>();
    
    File archivo;

    public void setArchivo(File archivo) {
        this.archivo = archivo;
    }
    
    boolean comboActivo = false;
    
    Principal principal;

    public void setPrincipal(Principal principal) {
        this.principal = principal;
    }
    
    public Salida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        timePicker1 = new com.raven.swing.TimePicker();
        background1 = new Diseño.Background();
        panelPrinc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new Diseño.Button();
        jLabel2 = new javax.swing.JLabel();
        labelNivel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFechaSalida = new javax.swing.JTextField();
        txtHoraSalida = new javax.swing.JTextField();
        btnHora = new javax.swing.JButton();
        btnRegistrar = new Diseño.Button();
        labelEmpleado = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelVehiculo = new javax.swing.JLabel();
        comboRegistro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        labelZona = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelHoraEntrada = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelFechaEntrada = new javax.swing.JLabel();

        dateChooser1.setDateFormat("dd/MM/yyyy");
        dateChooser1.setTextRefernce(txtFechaSalida);

        timePicker1.set24hourMode(true);
        timePicker1.setDisplayText(txtHoraSalida);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1.setBlur(panelPrinc);
        background1.setImage(new javax.swing.ImageIcon(getClass().getResource("/recursos/carroFondo7.jpg"))); // NOI18N

        panelPrinc.setOpaque(false);
        panelPrinc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Salida");
        panelPrinc.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 6, 495, -1));

        btnVolver.setText("Volver");
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelPrinc.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 390, 101, 44));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID Registro:");
        panelPrinc.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        labelNivel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelNivel.setForeground(new java.awt.Color(255, 255, 255));
        labelNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrinc.add(labelNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 100, 30));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Zona:");
        panelPrinc.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hora Entrada:");
        panelPrinc.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hora Salida:");
        panelPrinc.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cliente");
        panelPrinc.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Empleado");
        panelPrinc.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Vehículo");
        panelPrinc.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        txtFechaSalida.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        panelPrinc.add(txtFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 143, -1));

        txtHoraSalida.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtHoraSalida.setEnabled(false);
        panelPrinc.add(txtHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 143, -1));

        btnHora.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnHora.setText("...");
        btnHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoraActionPerformed(evt);
            }
        });
        panelPrinc.add(btnHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 38, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        panelPrinc.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 390, 115, 44));

        labelEmpleado.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        labelEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrinc.add(labelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 230, 24));

        labelCliente.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrinc.add(labelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 230, 24));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nombre:");
        panelPrinc.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nombre:");
        panelPrinc.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Marca:");
        panelPrinc.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        labelVehiculo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        labelVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrinc.add(labelVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 230, 24));

        comboRegistro.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        comboRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRegistroActionPerformed(evt);
            }
        });
        panelPrinc.add(comboRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 160, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nivel:");
        panelPrinc.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        labelZona.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelZona.setForeground(new java.awt.Color(255, 255, 255));
        labelZona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrinc.add(labelZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 170, 30));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Fecha Salida:");
        panelPrinc.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        labelHoraEntrada.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelHoraEntrada.setForeground(new java.awt.Color(255, 255, 255));
        labelHoraEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrinc.add(labelHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 160, 30));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Fecha Entrada:");
        panelPrinc.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        labelFechaEntrada.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelFechaEntrada.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrinc.add(labelFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 160, 30));

        background1.add(panelPrinc);
        panelPrinc.setBounds(30, 20, 810, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoraActionPerformed
        timePicker1.showPopup(this, 100, 100);
    }//GEN-LAST:event_btnHoraActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Registro registro = listaRegistros.get(comboRegistro.getSelectedIndex());
        registro.setFechaSalida(txtFechaSalida.getText());
        registro.setHoraSalida(txtHoraSalida.getText());
        TodoJson.modificarRegistro(archivo, registro);
        JOptionPane.showMessageDialog(this, "Se registro correctamente");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void comboRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRegistroActionPerformed
        if (!comboActivo) {
            return;
        }
        Registro registro = listaRegistros.get(comboRegistro.getSelectedIndex());
        labelNivel.setText(registro.getNivel());
        labelZona.setText(registro.getZona());
        labelFechaEntrada.setText(registro.getFechaIngreso());
        labelHoraEntrada.setText(registro.getHoraIngreso());
        labelCliente.setText(registro.getCliente().getNombresApellidos());
        labelEmpleado.setText(registro.getEmpleado().getNombresApellidos());
        labelVehiculo.setText(registro.getVehiculo().getMarcaModelo());
    }//GEN-LAST:event_comboRegistroActionPerformed

    public void rellenar(){
        comboActivo = false;
        listaRegistros = TodoJson.obtenerListaRegistros(archivo);
        comboRegistro.removeAllItems();
        if (!(listaRegistros.isEmpty())) {
            for(Registro registro : listaRegistros){
                comboRegistro.addItem(registro.getIdRegistro());
            }
            Registro registro = listaRegistros.get(0);
            labelNivel.setText(registro.getNivel());
            labelZona.setText(registro.getZona());
            labelFechaEntrada.setText(registro.getFechaIngreso());
            labelHoraEntrada.setText(registro.getHoraIngreso());
            labelCliente.setText(registro.getCliente().getNombresApellidos());
            labelEmpleado.setText(registro.getEmpleado().getNombresApellidos());
            labelVehiculo.setText(registro.getVehiculo().getMarcaModelo());
        }
        comboActivo = true;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Diseño.Background background1;
    private javax.swing.JButton btnHora;
    private Diseño.Button btnRegistrar;
    private Diseño.Button btnVolver;
    private javax.swing.JComboBox<String> comboRegistro;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JLabel labelFechaEntrada;
    private javax.swing.JLabel labelHoraEntrada;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelVehiculo;
    private javax.swing.JLabel labelZona;
    private javax.swing.JPanel panelPrinc;
    private com.raven.swing.TimePicker timePicker1;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtHoraSalida;
    // End of variables declaration//GEN-END:variables
}
